### ISSUE TITLE
Passwords containing an > break upload with ItunesTransporter

### ISSUE THREAD

**Issue by kommen** [fastlane/fastlane_core#118]
When the iTunes Connect user's password contains an `>` character, uploading builds using ItunesTransporter fails  with `[Transporter Error Output]: Your Apple ID or password was entered incorrectly. (-20101)`

The password works fine in the iTunes Connect login happing right before the upload is initiated.

I suspect the `Shellwords.escape` in `shell_escaped_password` is doing some shenanigans here?

**Comment by mfurtak** [comment]
Attn: @mpirri because I know he did some work in this area recently.

**Comment by mpirri** [comment]
Thanks for the info! The change that was made recently was to support single-quotes in passwords, but from what I'm hearing we are still having problems with <, >, [, ], and | (pipe). Definitely related to shellwords.escape'ing and how iTMSTransporter handles passwords on the command line. More work is required to make this right, but we will keep iterating until we get it working correctly!
