### ISSUE TITLE
Outdated fastlane_core causes issues.

### ISSUE THREAD

**Issue by lacostej** [fastlane/fastlane_core#31]
I've noticed that users have issues when they use an old fastlane_core. In particular if Apple broke the login process. It would be beneficial for the core to detect it is out of date and notify the users. So maybe this: https://fastlane-refresher.herokuapp.com/ should support fastlane_core ?

**Comment by KrauseFx** [comment]
Probably a good idea.

I'm usually trying to just update the dependencies to require the latest `fastlane_core`.

But that would be the same for `spaceship`, right? What was the issue that was caused by an outdated `fastlane_core`?

**Comment by lacostej** [comment]
On Sep 2, 2015 19:42, "Felix Krause" <notifications@github.com> wrote:
>
> Probably a good idea.
>
> I'm usually trying to just update the dependencies to require the latest
fastlane_core.
>
> But that would be the same for spaceship, right? What was the issue that
was caused by an outdated fastlane_core?

There were 2-3 issues causes by login changes con server. Itc cookies, etc

Those are bummer and affect anyone who sticks to old fastlane_core

J
